spring:
  application:
    name: user-service
  data:
    mongodb:
      database: userdb
      uri: mongodb://localhost:27017/userdb
#  datasource:
#    url: jdbc:postgresql://localhost:5432/userdb
#    username: postgres
#    password: admin
#  jpa:
#    show-sql: true
#    hibernate:
#      ddl-auto: update
#    database-platform: org.hibernate.dialect.PostgreSQLDialect
#    database: POSTGRESQL
#  h2:
#    console:
#      enabled: true
#  datasource:
#    url: jdbc:h2:mem:test
#  jpa:
#    show-sql: true
#    hibernate:
#      ddl-auto: create

server:
  port: 8082